[versions]
android-compileSdk = "36"
android-minSdk = "21"
android-targetSdk = "34"

# https://github.com/bumptech/glide/releases
glide = "5.0.5"

androidx-annotation = "1.9.1"
androidx-core = "1.17.0"
androidx-appcompat = "1.7.1"
androidx-fragment = "1.8.9"
androidx-drawerlayout = "1.2.0"
androidx-palette = "1.0.0"
androidx-preference = "1.2.1"
androidx-multidex = "2.0.1"
androidx-multidex-instrumentation = "2.0.0"
androidx-test-rules = "1.7.0"
androidx-test-runner = "1.7.0"
androidx-test-espresso = "3.7.0"

junit4 = "4.13.2"
jmh = "1.37"
hamcrest = "3.0"

# https://github.com/mockito/mockito/releases
mockito = "5.21.0"
mockito-kotlin = "6.2.3"

junit5 = "5.14.2"
junit5-androidtest = "1.9.0"

# TODEL https://issuetracker.google.com/issues/222730176 in root gradle when fixed.
# TODEL https://issuetracker.google.com/issues/378076280 in lint.xml/build.gradle when fixed.
agp = "8.13.2"

# https://github.com/TWiStErRob/net.twisterrob.gradle/releases
twisterrob = "0.19"

java = "11"
# https://github.com/JetBrains/kotlin/blob/master/ChangeLog.md
kotlin = "2.3.10"
# https://github.com/detekt/detekt/releases
kotlin-detekt = "2.0.0-alpha.2"

[libraries]
kotlin = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-detekt = { module = "dev.detekt:detekt-gradle-plugin", version.ref = "kotlin-detekt" }
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
twisterrob-quality = { module = "net.twisterrob.gradle:twister-quality", version.ref = "twisterrob" }
twisterrob-android = { module = "net.twisterrob.gradle:twister-convention-plugins", version.ref = "twisterrob" }

glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }

androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-appcompat-ktx = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }
androidx-test-fragment = { module = "androidx.fragment:fragment-testing", version.ref = "androidx-fragment" }
androidx-test-fragment-manifest = { module = "androidx.fragment:fragment-testing-manifest", version.ref = "androidx-fragment" }
androidx-drawerlayout = { module = "androidx.drawerlayout:drawerlayout", version.ref = "androidx-drawerlayout" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "androidx-preference" }
androidx-palette = { module = "androidx.palette:palette", version.ref = "androidx-palette" }
androidx-palette-ktx = { module = "androidx.palette:palette-ktx", version.ref = "androidx-palette" }
androidx-multidex = { module = "androidx.multidex:multidex", version.ref = "androidx-multidex" }
androidx-multidex-instrumentation = { module = "androidx.multidex:multidex-instrumentation", version.ref = "androidx-multidex-instrumentation" }
androidx-support = { group = "com.android.support", name = "unused" }

androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test-rules" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso" }

junit4 = { module = "junit:junit", version.ref = "junit4" }
junit5 = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit5" }
junit5-launcher = { module = "org.junit.platform:junit-platform-launcher" }
junit5-android = { module = "de.mannodermaus.junit5:android-test-core", version.ref = "junit5-androidtest" }
junit5-android-runner = { module = "de.mannodermaus.junit5:android-test-runner", version.ref = "junit5-androidtest" }

mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-android = { module = "org.mockito:mockito-android", version.ref = "mockito" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito-kotlin" }

hamcrest = { module = "org.hamcrest:hamcrest", version.ref = "hamcrest" }
jmh = { module = "org.openjdk.jmh:jmh-core", version.ref = "jmh" }
jmh-processor = { module = "org.openjdk.jmh:jmh-generator-annprocess", version.ref = "jmh" }

[bundles]

[plugins]
